name: Build RAPIDS project wheels

on:
  workflow_call:
    inputs:
      # repo and branch
      repo:
        type: string
      branch:
        type: string
      date:
        type: string
      sha:
        type: string
      build-type:
        required: true
        type: string

      package-name:
        required: true
        type: string
      package-dir:
        required: true
        type: string
      python-package-cuda-suffix:
        required: false
        type: string
        default: ''

      # versioneer and twine settings
      python-package-versioneer-override:
        required: false
        type: string
        default: ''
      python-package-build-tag:
        required: false
        type: string
        default: ''

      test-checkout-src:
        required: false
        type: string
        default: 'true'
      test-extras:
        required: false
        type: string
        default: ''
      test-unittest:
        required: false
        type: string
        default: ''
      test-before:
        required: false
        type: string
        default: 'true'

jobs:
  wheel-epoch-timestamp:
    name: wheel epoch timestamper
    runs-on: ubuntu-latest
    outputs:
      rapids_epoch_timestamp: ${{ steps.get_epoch_time.outputs.rapids_epoch_timestamp }}

    steps:
    - name: Get epoch timestamp to use as nightly version
      id: get_epoch_time
      run: echo "RAPIDS_EPOCH_TIMESTAMP=$(date +%s)" >> "${GITHUB_OUTPUT}"

  wheel-build:
    name: wheel build pure
    needs: wheel-epoch-timestamp
    runs-on: [self-hosted, linux, amd64, cpu4]
    container:
      image: "rapidsai/cibuildwheel_x86_64"
      env:
        RAPIDS_PY_WHEEL_CUDA_SUFFIX: ${{ inputs.python-package-cuda-suffix }}

    outputs:
      rapids_repository: ${{ steps.get_repo_info.outputs.rapids_repository }}
      rapids_sha: ${{ steps.get_repo_info.outputs.rapids_sha }}
      rapids_ref_name: ${{ steps.get_repo_info.outputs.rapids_ref_name }}
      rapids_nightly_date: ${{ steps.get_repo_info.outputs.rapids_nightly_date }}

    steps:
    - name: checkout code repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.sha }}
        fetch-depth: 0 # unshallow fetch for setuptools-scm
        persist-credentials: false

    - name: Standardize repository information
      id: get_repo_info
      run: |
        echo "RAPIDS_REPOSITORY=${{ inputs.repo || github.repository }}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        echo "RAPIDS_SHA=$(git rev-parse HEAD)" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        echo "RAPIDS_REF_NAME=${{ inputs.branch || github.ref_name }}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"
        echo "RAPIDS_NIGHTLY_DATE=${{ inputs.date }}" | tee --append "${GITHUB_ENV}" "${GITHUB_OUTPUT}"

    - name: Build pure python wheel with pip wheel
      run: |
        versioneer_override="${{ inputs.python-package-versioneer-override }}"

        if [ "${versioneer_override}" == "" ]; then
          versioneer_override="$(rapids-pip-wheel-version ${{ needs.wheel-epoch-timestamp.outputs.rapids_epoch_timestamp }})"
        fi
          
        export RAPIDS_PY_WHEEL_VERSIONEER_OVERRIDE="${versioneer_override}"
        python -m pip wheel -w ./dist ${{ inputs.package-dir }} --no-deps
      shell: bash

    - name: Upload wheels to downloads.rapids.ai
      run: rapids-upload-wheels-to-s3 dist
      env:
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}
        RAPIDS_BUILD_TYPE: ${{ inputs.build-type }}
        RAPIDS_PY_VERSION: "3.8"
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}

  wheel-test:
    name: wheel test pure
    runs-on: [self-hosted, linux, amd64, gpu-v100-495-1]
    needs: wheel-build
    container:
      image: "rapidsai/citestwheel_x86_64"
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }} # GPU jobs must set this container env variable
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}
        RAPIDS_CPYTHON_VERSION: "cp38"
        RAPIDS_PY_VERSION: "3.8"
        RAPIDS_BUILD_TYPE: ${{ inputs.build-type }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}
        RAPIDS_BEFORE_TEST_COMMANDS_AMD64: ${{ inputs.test-before }}
        CIBW_TEST_EXTRAS: ${{ inputs.test-extras }}
        CIBW_TEST_COMMAND: ${{ inputs.test-unittest }}
    steps:
    - name: Run nvidia-smi to make sure GPU is working
      run: nvidia-smi

    - name: Install private index credentials in cibuildwheel container
      run: printf 'machine pypi.k8s.rapids.ai\n\tlogin cibuildwheel\n\tpassword ${{ secrets.RAPIDSAI_PYPI_CI_PASSWORD }}\n' > ~/.netrc

    - name: checkout code repo
      uses: actions/checkout@v3
      if: ${{ inputs.test-checkout-src == 'true' }}
      with:
        repository: ${{ inputs.repo }}
        ref: ${{ inputs.sha }}
        fetch-depth: 0 # unshallow fetch for setuptools-scm
        persist-credentials: false

    - name: Get repository information from build step
      run: |
        echo "RAPIDS_REPOSITORY=${{ needs.wheel-build.outputs.rapids_repository }}" >> "${GITHUB_ENV}"
        echo "RAPIDS_SHA=${{ needs.wheel-build.outputs.rapids_sha }}" >> "${GITHUB_ENV}"
        echo "RAPIDS_REF_NAME=${{ needs.wheel-build.outputs.rapids_ref_name }}" >> "${GITHUB_ENV}"
        echo "RAPIDS_NIGHTLY_DATE=${{ needs.wheel-build.outputs.rapids_nightly_date }}" >> "${GITHUB_ENV}"

    - name: Run citestwheel
      run: /citestwheel.sh

  wheel-publish:
    name: wheel publish pure
    needs: [wheel-build, wheel-test]
    runs-on: [self-hosted, linux, amd64, cpu4]
    container:
      image: rapidsai/cibuildwheel_x86_64
      env:
        RAPIDS_PY_WHEEL_NAME: ${{ inputs.package-name }}
        RAPIDS_PY_WHEEL_BUILD_TAG: ${{ inputs.python-package-build-tag }}
        RAPIDS_BUILD_TYPE: ${{ inputs.build-type }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RAPIDSAI_GHA_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RAPIDSAI_GHA_AWS_SECRET_ACCESS_KEY }}
        TWINE_USERNAME: cibuildwheel
        TWINE_PASSWORD: ${{ secrets.RAPIDSAI_PYPI_CI_PASSWORD }}
        TWINE_REPOSITORY_URL: "https://pypi.k8s.rapids.ai/simple/"
    steps:
    - name: Get repository information from build step
      run: |
        echo "RAPIDS_REPOSITORY=${{ needs.wheel-build.outputs.rapids_repository }}" >> "${GITHUB_ENV}"
        echo "RAPIDS_SHA=${{ needs.wheel-build.outputs.rapids_sha }}" >> "${GITHUB_ENV}"
        echo "RAPIDS_REF_NAME=${{ needs.wheel-build.outputs.rapids_ref_name }}" >> "${GITHUB_ENV}"
        echo "RAPIDS_NIGHTLY_DATE=${{ needs.wheel-build.outputs.rapids_nightly_date }}" >> "${GITHUB_ENV}"

    - name: Download wheels from downloads.rapids.ai and publish to internal PyPI
      run: |
        RAPIDS_PY_VERSION="3.8" rapids-download-wheels-from-s3 ./dist
        rapids-twine ./dist/
